### ISSUE TITLE
On the proof of Lemma 1

### ISSUE THREAD

**Issue by q-yang** [CasperLabs/highway#16]
First thank you for this interesting paper. It is really solid piece of work! However, the mathematical part is sort of abstract and hard to understand. 

I got stuck at the proof of Lemma 1. The inequality equation (2) is confusing, how do you prove it?

Also, in the definition of (q,k)-summit, what is the intuition behind the "nested sets"? Can I let C1=C2=....=Ck=C0, so that k can be any integer number?

**Comment by afck** [comment]
> The inequality equation (2) is confusing, how do you prove it?

That's the induction hypothesis: We prove
"|A(u)| ≥ (2q - n) (1 - 2<sup>-k</sup>) if D(u) doesn't intersect C<sub>k</sub> and u doesn't vote for B"
by induction over k, so we can assume it's true for k - 1. That means inequality (2) because D(u') doesn't intersect C<sub>k - 1</sub> and u' doesn't vote for B.

> what is the intuition behind the "nested sets"?

Something like:
C<sub>0</sub> are votes for B.
C<sub>1</sub> are units that see a sufficient majority (i.e. weight ≥ q) of votes for B.
C<sub>2</sub> are units that see a sufficient majority of units that see a sufficient majority of votes for B.
etc.

> Can I let C1=C2=....=Ck=C0, so that k can be any integer number?

In general such a summit won't exist.
(Except if a single validator alone has weight q: Then a single vote by that validator is already a summit of arbitrary height.)

**Comment by bradjohnl** [comment]
Closing this issue as the repository is getting archived
